### ISSUE TITLE
code_32 has excessive runtime and failures in node tests vs browser

### ISSUE THREAD

**Issue by ericblade** [ericblade/quagga2#435]
browser results:
```    Decoder code_32
      √ decodes image-1.jpg (75ms)
      √ decodes image-2.jpg (483ms)
      √ decodes image-3.jpg (457ms)
      √ decodes image-4.jpg (443ms)
      √ decodes image-5.jpg (496ms)
      √ decodes image-6.jpg (492ms)
      √ decodes image-7.jpg (442ms)
      √ decodes image-8.jpg (483ms)
      √ decodes image-9.jpg (471ms)
      √ decodes image-10.jpg (448ms)
```
node results:
```
    Decoder code_32
      √ decodes image-1.jpg (70ms)
Trace: * error during test AssertionError: expected null to be an object
    at Context.<anonymous> (C:\src\quagga2\test\integration\integration.spec.ts:39:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\quagga2\test\integration\integration.spec.ts:5:58) {
  showDiff: false,
  actual: null,
  expected: undefined,
  operator: 'strictEqual'
}
    at C:\src\quagga2\test\integration\integration.spec.ts:20:25
      - decodes image-2.jpg
Trace: * error during test AssertionError: expected [] to be an object
    at Context.<anonymous> (C:\src\quagga2\test\integration\integration.spec.ts:39:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\quagga2\test\integration\integration.spec.ts:5:58) {
  showDiff: false,
  actual: [],
  expected: undefined,
  operator: 'strictEqual'
}
    at C:\src\quagga2\test\integration\integration.spec.ts:20:25
      - decodes image-3.jpg
      √ decodes image-4.jpg (958ms)
      √ decodes image-5.jpg (920ms)
Trace: * error during test AssertionError: expected [] to be an object
    at Context.<anonymous> (C:\src\quagga2\test\integration\integration.spec.ts:39:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\quagga2\test\integration\integration.spec.ts:5:58) {
  showDiff: false,
  actual: [],
  expected: undefined,
  operator: 'strictEqual'
}
    at C:\src\quagga2\test\integration\integration.spec.ts:20:25
      - decodes image-6.jpg
Trace: * error during test AssertionError: expected null to be an object
    at Context.<anonymous> (C:\src\quagga2\test\integration\integration.spec.ts:39:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\quagga2\test\integration\integration.spec.ts:5:58) {
  showDiff: false,
  actual: null,
  expected: undefined,
  operator: 'strictEqual'
}
    at C:\src\quagga2\test\integration\integration.spec.ts:20:25
      - decodes image-7.jpg
Trace: * error during test AssertionError: expected null to be an object
    at Context.<anonymous> (C:\src\quagga2\test\integration\integration.spec.ts:39:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\src\quagga2\test\integration\integration.spec.ts:5:58) {
  showDiff: false,
  actual: null,
  expected: undefined,
  operator: 'strictEqual'
}
    at C:\src\quagga2\test\integration\integration.spec.ts:20:25
      - decodes image-8.jpg
      √ decodes image-9.jpg (1007ms)
      √ decodes image-10.jpg (904ms)
```

**Comment by ericblade** [comment]
@stefanocali any chance you might be able to look into why running code_32 in node produces a large number of failures but in browser it does not?  also might be a reason for why it seemingly takes twice as long to complete

**Comment by ericblade** [comment]
@stefanocali I've spent some time narrowing it down, it doesn't look to be a problem with the code you submitted, as quagga.ts#locateAndDecode is getting a null result from ```const boxes = this.getBoundingBoxes()``` on test #2 ... test #3 is failing in a different fashion, but the code 39 reader is also failing on it.

I'm going to try to spend some time to nail it down, but if you might have any thoughts on why BarcodeLocator seems to be failing on that image vs in browser, chime in :)

Thanks!

**Comment by ericblade** [comment]
closing this for now in favor of https://github.com/ericblade/quagga2/issues/436

will try to chase this down, and hopefully finding and fixing that will fix the remaining issues.  if not, there may be more to investigate
